//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.cloud.prospect.FtpWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ikang.com/", ConfigurationName="FtpWebService.WsPacsTransSoap")]
    public interface WsPacsTransSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikang.com/SaveCheckImages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        bool SaveCheckImages(string XMLString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikang.com/SaveSummary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        bool SaveSummary(long CheckItemsID, string Content, long UserID, string RecordDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikang.com/SaveCheckItemIndexResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        bool SaveCheckItemIndexResult(long CheckItemsID, long ItemIndexID, string ItemIndexResultTempletDescription, string ItemIndexResultValue, string ItemIndexResultDetail, string ItemIndexResultDiagnose, string ItemIndexResultDiagnoseDetail, string ItemIndexResultAdvice, bool IsExeception, long UserID, string RecordDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikang.com/UpdateCheckItemsState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        bool UpdateCheckItemsState(long CheckItemsID, int CheckStateID, int DepartmentID, long UserID, string RecordDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ikang.com/SyncDictionary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string SyncDictionary();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsPacsTransSoapChannel : com.cloud.prospect.FtpWebService.WsPacsTransSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsPacsTransSoapClient : System.ServiceModel.ClientBase<com.cloud.prospect.FtpWebService.WsPacsTransSoap>, com.cloud.prospect.FtpWebService.WsPacsTransSoap {
        
        public WsPacsTransSoapClient() {
        }
        
        public WsPacsTransSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsPacsTransSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPacsTransSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsPacsTransSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveCheckImages(string XMLString) {
            return base.Channel.SaveCheckImages(XMLString);
        }
        
        public bool SaveSummary(long CheckItemsID, string Content, long UserID, string RecordDate) {
            return base.Channel.SaveSummary(CheckItemsID, Content, UserID, RecordDate);
        }
        
        public bool SaveCheckItemIndexResult(long CheckItemsID, long ItemIndexID, string ItemIndexResultTempletDescription, string ItemIndexResultValue, string ItemIndexResultDetail, string ItemIndexResultDiagnose, string ItemIndexResultDiagnoseDetail, string ItemIndexResultAdvice, bool IsExeception, long UserID, string RecordDate) {
            return base.Channel.SaveCheckItemIndexResult(CheckItemsID, ItemIndexID, ItemIndexResultTempletDescription, ItemIndexResultValue, ItemIndexResultDetail, ItemIndexResultDiagnose, ItemIndexResultDiagnoseDetail, ItemIndexResultAdvice, IsExeception, UserID, RecordDate);
        }
        
        public bool UpdateCheckItemsState(long CheckItemsID, int CheckStateID, int DepartmentID, long UserID, string RecordDate) {
            return base.Channel.UpdateCheckItemsState(CheckItemsID, CheckStateID, DepartmentID, UserID, RecordDate);
        }
        
        public string SyncDictionary() {
            return base.Channel.SyncDictionary();
        }
    }
}
